#!/bin/bash

account=$1;
accountfolder=/app/sword/shared/ftpserver/customer/${account};

if [[ ! -d ${accountfolder} ]]; then
    echo "Account ${account} does not exist.";
    exit;
fi

echo "Please input the key you want to add to ${account}:";
read keycontent;

if [[ ! -f ${accountfolder}/.sftp/authorized_keys ]]; then
    mkdir -p ${accountfolder}/.sftp;
    touch ${accountfolder}/.sftp/authorized_keys;

    accountID=$(grep -w ${accountfolder} /app/sword/ftpserver/etc/proftpd_passwd | cut -d: -f3);
    if [[ -z "${accountID}" ]]; then
        echo "Failed to fetch UID for account ${account}";
        exit;
    fi

    chown -R ${accountID}:b2bi ${accountfolder}/.sftp;
    chmod 700 ${accountfolder}/.sftp;
    chmod 600 ${accountfolder}/.sftp/authorized_keys;
fi

echo "${keycontent}" > /tmp/public_key_${account};
ssh-keygen -e -f /tmp/public_key_${account} > /dev/null;
if [[ $? != 0 ]]; then
    /usr/bin/rm /tmp/public_key_${account};
    exit;
fi
ssh-keygen -e -f /tmp/public_key_${account} >> ${accountfolder}/.sftp/authorized_keys;
/usr/bin/rm /tmp/public_key_${account};

