#!/bin/bash

function check_param()
{
    if [[ "" != "$1" ]];then
        if [[ "-v" == "$1" ]];then
            echo "*********************************************************";
            echo "clean_up3 - verbose mode - show what's being (re-)moved. ";
            echo "*********************************************************";
        else
            echo "syntax: $0 [-v]";
            echo "   -v: verbose. print what will be (re)moved";
            exit 1;
        fi
    fi
}

function main()
{
    check_param $@;
    ./clean_up3_ex_a1.sh;
}

main;
